/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var caseylucas_second_v1_widget_pb = require('../../../caseylucas/second/v1/widget_pb.js');
goog.exportSymbol('proto.caseylucas.second.v1.AddWidgetRequest', null, global);
goog.exportSymbol('proto.caseylucas.second.v1.AddWidgetResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.caseylucas.second.v1.AddWidgetRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.caseylucas.second.v1.AddWidgetRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.caseylucas.second.v1.AddWidgetRequest.displayName = 'proto.caseylucas.second.v1.AddWidgetRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.caseylucas.second.v1.AddWidgetRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.caseylucas.second.v1.AddWidgetRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.caseylucas.second.v1.AddWidgetRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.caseylucas.second.v1.AddWidgetRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    widget: (f = msg.getWidget()) && caseylucas_second_v1_widget_pb.Widget.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.caseylucas.second.v1.AddWidgetRequest}
 */
proto.caseylucas.second.v1.AddWidgetRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.caseylucas.second.v1.AddWidgetRequest;
  return proto.caseylucas.second.v1.AddWidgetRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.caseylucas.second.v1.AddWidgetRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.caseylucas.second.v1.AddWidgetRequest}
 */
proto.caseylucas.second.v1.AddWidgetRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new caseylucas_second_v1_widget_pb.Widget;
      reader.readMessage(value,caseylucas_second_v1_widget_pb.Widget.deserializeBinaryFromReader);
      msg.setWidget(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.caseylucas.second.v1.AddWidgetRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.caseylucas.second.v1.AddWidgetRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.caseylucas.second.v1.AddWidgetRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.caseylucas.second.v1.AddWidgetRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWidget();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      caseylucas_second_v1_widget_pb.Widget.serializeBinaryToWriter
    );
  }
};


/**
 * optional Widget widget = 1;
 * @return {?proto.caseylucas.second.v1.Widget}
 */
proto.caseylucas.second.v1.AddWidgetRequest.prototype.getWidget = function() {
  return /** @type{?proto.caseylucas.second.v1.Widget} */ (
    jspb.Message.getWrapperField(this, caseylucas_second_v1_widget_pb.Widget, 1));
};


/** @param {?proto.caseylucas.second.v1.Widget|undefined} value */
proto.caseylucas.second.v1.AddWidgetRequest.prototype.setWidget = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.caseylucas.second.v1.AddWidgetRequest.prototype.clearWidget = function() {
  this.setWidget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.caseylucas.second.v1.AddWidgetRequest.prototype.hasWidget = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.caseylucas.second.v1.AddWidgetResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.caseylucas.second.v1.AddWidgetResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.caseylucas.second.v1.AddWidgetResponse.displayName = 'proto.caseylucas.second.v1.AddWidgetResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.caseylucas.second.v1.AddWidgetResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.caseylucas.second.v1.AddWidgetResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.caseylucas.second.v1.AddWidgetResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.caseylucas.second.v1.AddWidgetResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    widget: (f = msg.getWidget()) && caseylucas_second_v1_widget_pb.Widget.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.caseylucas.second.v1.AddWidgetResponse}
 */
proto.caseylucas.second.v1.AddWidgetResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.caseylucas.second.v1.AddWidgetResponse;
  return proto.caseylucas.second.v1.AddWidgetResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.caseylucas.second.v1.AddWidgetResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.caseylucas.second.v1.AddWidgetResponse}
 */
proto.caseylucas.second.v1.AddWidgetResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new caseylucas_second_v1_widget_pb.Widget;
      reader.readMessage(value,caseylucas_second_v1_widget_pb.Widget.deserializeBinaryFromReader);
      msg.setWidget(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.caseylucas.second.v1.AddWidgetResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.caseylucas.second.v1.AddWidgetResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.caseylucas.second.v1.AddWidgetResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.caseylucas.second.v1.AddWidgetResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWidget();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      caseylucas_second_v1_widget_pb.Widget.serializeBinaryToWriter
    );
  }
};


/**
 * optional Widget widget = 1;
 * @return {?proto.caseylucas.second.v1.Widget}
 */
proto.caseylucas.second.v1.AddWidgetResponse.prototype.getWidget = function() {
  return /** @type{?proto.caseylucas.second.v1.Widget} */ (
    jspb.Message.getWrapperField(this, caseylucas_second_v1_widget_pb.Widget, 1));
};


/** @param {?proto.caseylucas.second.v1.Widget|undefined} value */
proto.caseylucas.second.v1.AddWidgetResponse.prototype.setWidget = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.caseylucas.second.v1.AddWidgetResponse.prototype.clearWidget = function() {
  this.setWidget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.caseylucas.second.v1.AddWidgetResponse.prototype.hasWidget = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.caseylucas.second.v1);
